### PR TITLE
Fixing unittests

### PR DESCRIPTION
**Pull request by pkamps**
Unittest were pretty broken/not maintained. So even if this pull request is not perfectly fixing the unit tests, it's huge step forward.

### CODE REVIEW

**Comment by pkamps** [comment]
Original pull request:
https://github.com/ezsystems/ezfind/pull/76

**Comment by pkamps** [comment]
This is depending on
https://github.com/mugoweb/ezpublish-legacy/pull/32

**Comment by benkmugo** [comment]
@pkamps just adding this here to keep track

With the dependency of the ezpublish PR in place, the unit tests work well, with the exception of the HTTP request timeout test, which fails with the following message:
```
There was 1 failure:

1) eZSolrBaseRegression::testSendHTTPRequestRetryTimeout
Sending HTTP Request to Solr must be retried a setted number of times (in solr.ini) if server has timed out
Failed asserting that 4 matches expected 40.

/var/www/ezp/extension/ezfind/tests/classes/ezsolrbase_regression.php:99
```

I'm not convinced this is an issue in general and may be related to the test VM setup somehow, but I haven't looked into it further yet.

**Comment by benkmugo** [comment]
Have you had a chance to see if you can replicate that one test issue on your local @pkamps ?

**Comment by pkamps** [comment]
That test checks if the timeout and retry configuration for a solr connection is working correctly. The test is actually running fine for me:
4 (timediff) == 4 ( $connectionTimeout * $maxRetries ) in
/var/www/ezp/extension/ezfind/tests/classes/ezsolrbase_regression.php:99

The $connectionTimeout and $maxRetries is set in
/var/www/ezp/extension/ezfind/tests/classes/ezsolrbase_regression.php::setUp (Line 39).

That does not seem to work in your environment, because $connectionTimeout * $maxRetries is 40 for you.

If you like we do a shared screen session and debug the issue.

**Pull request merged**
