### PR TITLE
Add IP Access Handler to Solr's jetty configuration

### PR DESCRIPTION
**Pull request by benkmugo**
- updating the existing jetty configuration by wrapping the
ContextHandlerCollection handler with the IPAccessHandler
allows white/black lists to be configured to grant/deny access to
specified IPs.

### CODE REVIEW

**Comment by peterkeung** [comment]
On a client install of eZ Publish 5.4, I couldn't get both browser access and eZ access to work at the same time.

With the "host" value in "SocketConnector" as 127.0.0.1, the whitelist didn't have any effect when adding an additional IP.

With the "host" value in "SocketConnector" empty, the whitelist (with 1 or 2 IPs) worked to access the Solr interface in my browser (domain:8983/solr) but then the eZ search broke. I tried IPv6 (::1) but then Solr wouldn't start at all.

**Comment by benkmugo** [comment]
Setting a any value for "host" in the socket connector will block access to the admin UI as it cuts off access at an earlier point, before the IPHandler kicks in.

If you leave the the settings as `<Set name="host"><SystemProperty name="jetty.host" /></Set>` you should then be able to use the white/blacklist feature.

The 127.0.0.1 entry should retain access for eZ and the second IP access for the browser.
At least that what I am seeing locally on a 5.4 install.

**Comment by pkamps** [comment]
With
`<Set name="host"><SystemProperty name="jetty.host" /></Set>`

you control on which network device solr will listen on. Typically on a server you have the loop device 127.0.0.1 and network device out to the internet. If you don't specify anything, solr will listen on all network devices.

The `IPAccessHandler` is something like a firewall. Filtering access based on the client IP address. If ezp is installed on the same host, it usually uses 127.0.0.1 to access solr. If you like to allow a webbrowser to access solr over the internet, you would need to make sure that:
* solr is listening on the network device that goes to the internet
* you have your ISP IP (in most cases dynamic) configured in `IPAccessHandler`

**Comment by pkamps** [comment]
I think the long time goal should be to have solr only listening to the loop device (or an internal network device in case solr is not on the same server). Because we don't want to open up the port 8983 to the public - it makes the server a little more vulnerable to attacks.

I understand that the solr admin interface has great tools to debug/work with the index. Maybe we can extend our custom solr admin interface (http://devmanage.lovestack.mugo.ca/ezfind/query) to support all features we usually need when debugging/working with the solr index.

That said, this pull request is allowing us to have more configuration options - we don't have to use them. So I think it would be a good addition.

Maybe we add some inline documentation to make things a little more clear:
* `<Set name="host"><SystemProperty name="jetty.host" /></Set>` - use it to control on which device solr is listening
* `IPAccessHandler` - use it to control access to solr based on the client IP - might not be required if you restrict the access with `<Set name="host"><SystemProperty name="jetty.host" /></Set>`

**Comment by benkmugo** [comment]
Killing this. We have since moved on to keeping Solr internal and accessing via tunnel if need be.

**Pull request closed without merging**
