### PR TITLE
Fix EZP-23541

### PR DESCRIPTION
**Pull request by benkmugo**
- updated RHEL Solr startup script daemon setup and finding pid

### CODE REVIEW

**Comment by pkamps** [comment]
Is the PID not stored in this file? /var/run/$NAME.pid

**Comment by benkmugo** [comment]
That's a very good point actually. I just focused on the extraction from ps like the previous code. Getting it from the pid file is likely a better alternative?

**Comment by pkamps** [comment]
To me, woking with regular expressions is often a bit hackish. It proofed to be not reliable - that's why we have this pull request.
I would try to use what you have in `d_status()` or even call that function:
```
status -p /var/run/solr.pid "$NAME" > /dev/null 2>&1
// then check value of $?
```

**Comment by benkmugo** [comment]
Closing this as well. Philipp's suggestion would have been the better approach.
The script had other issues and we have since moved on use the [service unit files](https://github.com/mugoweb/ezfind/blob/master/bin/scripts/rhel/solr.service)

**Pull request closed without merging**
